var WIDTH = 8000;
var HEIGHT = 8000;
var TILES = 20000;
var SHARDS = 200;
var SHARD_WIDTH = 10;
var BORDER_WIDTH = 100;

module.exports = {
    WIDTH: WIDTH,
    HEIGHT: HEIGHT,
    TILES: TILES,
    SHARDS: SHARDS,
    SHARD_WIDTH: SHARD_WIDTH,
    BORDER_WIDTH: BORDER_WIDTH
};