var WIDTH = 2000;
var HEIGHT = 2000;
var TILES = 16;
var SHARDS = 80;
var SHARD_WIDTH = 10;

module.exports = {
    WIDTH: WIDTH,
    HEIGHT: HEIGHT,
    TILES: TILES,
    SHARDS: SHARDS,
    SHARD_WIDTH: SHARD_WIDTH
};