var WIDTH = 10000;
var HEIGHT = 10000;
var TILES = 2000;
var SHARDS = 50;
var SHARD_WIDTH = 10;
var BORDER_WIDTH = 100;

module.exports = {
    WIDTH: WIDTH,
    HEIGHT: HEIGHT,
    TILES: TILES,
    SHARDS: SHARDS,
    SHARD_WIDTH: SHARD_WIDTH,
    BORDER_WIDTH: BORDER_WIDTH
};